language: node_js
node_js:
  - "node"
  - "12"
  - "8"
  - "6"
  - "4"
install: npm install
script:
  - echo $TRAVIS_NODE_VERSION
  - npm test
  - npm build
env:
  matrix:
    secure: G5V8fwLUc98lo5lUf/y6hnziq+k924NrY4M/l8A6z5cHYs66WNWTZe5fs30wjylkLTgT1SDFHBoGNpl2B3rLH8Bt9rZf4PB01XidHXp1S7OJh5BYcLMsN9UgBIi8il61iLXpkLqVX9qH/j8Drr9V5blbA3SoU+cnEIzHY+S4kFo=
notifications:
  slack:
    secure: eWKjw1J4ua7e6/USQwcJOLiJXBTrgF+5sELqKcUsGVTvnzuflmvUDBk0opx8zpfOdSotWbk8+r2zvT0KWDNQGBhUTmjROkfNd+n6+n8xl6/LkyhDWSImK39ljKmreOfI+a9M3rQcw9rwt1WyIfqkOmna8utffuzIAXOH0QAtiAQ=
